# Generated by Django 2.2.16 on 2022-03-06 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genretitles',
            old_name='titles',
            new_name='title',
        ),
    ]
