# Generated by Django 2.2.16 on 2022-03-07 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220306_2230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Genres',
        ),
    ]
