# Generated by Django 2.2.16 on 2022-03-07 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220307_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(message='Неккоректное поле slug', regex='^[-a-zA-Z0-9_]+$')]),
        ),
    ]
